### PR TITLE
Update recipe

### PR DESCRIPTION
**Pull request by ocefpaf**
Needs https://github.com/conda-forge/ncl-feedstock/pull/41

### CODE REVIEW

**Comment by khallock** [comment]
As soon as conda-forge/ncl-feedstock#41 finishes (and the new NCL build is uploaded to the Anaconda cloud), I'll push a new commit to this PR that re-enables XQuartz.

**Comment by ocefpaf** [comment]
> As soon as conda-forge/ncl-feedstock#41 finishes (and the new NCL build is uploaded to the Anaconda cloud), I'll push a new commit to this PR that re-enables XQuartz.

Thanks! https://github.com/conda/conda/issues/7626 hit us pretty hard and we are only working around it until a better solution is in place.

**Comment by khallock** [comment]
Thanks for the help today, @ocefpaf and @isuruf!

**Comment by ocefpaf** [comment]
@khallock if you and people on your group are hitting the channel mixing issue frequently consider adding your :+1: to [this issue](https://github.com/conda/conda/issues/7656) to help them prioritize it and hopefully fix this situation.

**Comment by khallock** [comment]
@ocefpaf, I just 👍'ed that issue. Thanks for bringing that up, a "strict" option would definitely help keep our packages working without needing to rebuild/re-pin as often.

**Pull request merged**
